remote_theme: pmarsceill/just-the-docs

title: Just the Docs
description: A Jekyll theme for documentation
baseurl: "/blog" # subpath of your site
url: "https://sylvesterlau.com" # the base hostname & protocol for your site
